version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  service:
#    image: maven:3.8.7-openjdk-18
#    volumes:
#      - ../:/app
#    working_dir: /app/service
#    command:
#      - mvn compile
#      - mvn jetty:run
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres

volumes:
  postgres_data:
